services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /home/poca/Documents/Services/redis/data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - 8086:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
